version: '3.7'

volumes:
  mongodb_DB2:
  mongodb_conf2:

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_DB2:/data/db
      - mongodb_conf2:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

