version: '3.7'

volumes:
  mongodb_DB:
  mongodb_conf:

networks: 
  app:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_DB:/data/db
      - mongodb_conf:/data/configdb
    ports:
      - 27017:27017
    networks: 
      - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app

  app:
    image: ghcr.io/tls-anonymous/tls-anvil-result-analyzer:latest
    restart: always
    environment: 
      PRODUCTION: '1'
    build: 
      context: .
      args:
        REST_API_BASE_URL: http://localhost:5000/api/v1
    ports:
      - 5000:5000
    networks:
      - app
      

